name: .NET Ci
on:
  push:
    branches: 
     - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup.NET
        uses: actions/setup-dotnet@v4
        with: 
           dotnet-version: 8.0.x

      - run: dotnet restore
      - run: dotnet build --no-restore



  unit-test:
    runs-on: windows-latest
    needs: build
    steps:  
      - uses: actions/checkout@v4
      - name: Setup.NET
        uses: actions/setup-dotnet@v4
        with: 
           dotnet-version: 8.0.x

      - run: dotnet restore
      - run: dotnet test --filter "Category=Unit"
       

  int-test:
    runs-on: windows-latest
    needs: unit-tests
    steps:  
      - uses: actions/checkout@v4
      - name: Setup.NET
        uses: actions/setup-dotnet@v4
        with: 
           dotnet-version: 8.0.x

      - run: dotnet restore
      - run: dotnet test --filter "Category=Integration"